export const actionTypes = {
    USER_REGISTER = "USER_REGISTER",
    USER_LOGIN = "USER_LOGIN",
    USER_LOGOUT = "USER_LOGOUT",
    GET_ALL_PRODUCT = "GET_ALL_PRODUCT",
    GET_SIGNLE_PRODUCT = "GET_SIGNLE_PRODUCT",
    ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART",
    DELETE_FROM_CART = "DELETE_FROM_CART",
    BUY_PRODUCT = "BUY_PRODUCT",
    ADD_PRODUCT_QUANTITY = "ADD_PRODUCT_QUANTITY",
    DELETE_PRODUCT_QUANTITY = "DELETE_PRODUCT_QUANTITY",
    VIEW_CART_ITEMS = "VIEW_CART_ITEMS",
}